(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const page=(location.pathname.split('/').pop()||'admin-dashboard.html').toLowerCase();
const state={ctx:null};
const ICONS={
 home:'<svg viewBox="0 0 24 24"><path d="M3 11.5 12 4l9 7.5"/><path d="M5.5 10.5V20h13v-9.5"/><path d="M9.5 20v-6h5v6"/></svg>',
 testing:'<svg viewBox="0 0 24 24"><path d="M9 3h6"/><path d="M10 3v5l-4.5 8.4A3 3 0 0 0 8.1 21h7.8a3 3 0 0 0 2.6-4.6L14 8V3"/><path d="M7.5 15h9"/></svg>',
 training:'<svg viewBox="0 0 24 24"><path d="m3 8 9-4 9 4-9 4-9-4Z"/><path d="M7 10.2V15c0 1.8 2.2 3 5 3s5-1.2 5-3v-4.8"/><path d="M21 8v6"/></svg>',
 workforce:'<svg viewBox="0 0 24 24"><circle cx="8" cy="8" r="3"/><circle cx="17" cy="9" r="2.5"/><path d="M2.5 20c.4-4 2.5-6 5.5-6s5.1 2 5.5 6"/><path d="M13 16c1-.9 2.2-1.4 3.8-1.4 2.5 0 4 1.6 4.7 4.4"/></svg>',
 dot:'<svg viewBox="0 0 24 24"><path d="M4 6h11v10H4z"/><path d="M15 9h3l2 3v4h-5z"/><circle cx="8" cy="18" r="2"/><circle cx="17.5" cy="18" r="2"/></svg>',
 assignments:'<svg viewBox="0 0 24 24"><path d="M4 5h16v14H4z"/><path d="M8 3v4M16 3v4M4 9h16"/><path d="M8 13h3M8 16h6"/></svg>',
 finance:'<svg viewBox="0 0 24 24"><path d="M4 7h16v12H4z"/><path d="M4 10h16"/><path d="M8 15h3"/><path d="M7 4h10"/></svg>',
 crm:'<svg viewBox="0 0 24 24"><path d="M4 5h16v11H8l-4 4V5Z"/><path d="M8 9h8M8 12h5"/></svg>',
 schedule:'<svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4M17 3v4M3 10h18"/><path d="M8 14h3M13 14h3M8 17h3"/></svg>',
 docs:'<svg viewBox="0 0 24 24"><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v5h5M9 13h6M9 17h6"/></svg>',
 staff:'<svg viewBox="0 0 24 24"><circle cx="8" cy="8" r="3"/><path d="M3 20c.5-4 2.4-6 5-6s4.5 2 5 6"/><path d="M16 7h5M18.5 4.5v5M16 14h5M16 18h5"/></svg>',
 audit:'<svg viewBox="0 0 24 24"><path d="M12 3l7 3v5c0 4.8-2.7 8.1-7 10-4.3-1.9-7-5.2-7-10V6l7-3Z"/><path d="M9 12l2 2 4-4"/></svg>',
 settings:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"/><path d="M19 12a7 7 0 0 0-.1-1l2-1.5-2-3.4-2.4 1a7.5 7.5 0 0 0-1.8-1L14.4 3h-4.8l-.4 3.1a7.5 7.5 0 0 0-1.8 1l-2.4-1-2 3.4L5 11a7 7 0 0 0 0 2l-2 1.5 2 3.4 2.4-1a7.5 7.5 0 0 0 1.8 1l.4 3.1h4.8l.4-3.1a7.5 7.5 0 0 0 1.8-1l2.4 1 2-3.4L19 13a7 7 0 0 0 0-1Z"/></svg>',
 tech:'<svg viewBox="0 0 24 24"><path d="M8 12h8M12 8v8"/><rect x="4" y="4" width="16" height="16" rx="3"/></svg>',
 help:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M9.7 9a2.5 2.5 0 1 1 4.4 1.7c-.9.9-2.1 1.2-2.1 2.8M12 17h.01"/></svg>',
 search:'<svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg>',
 bell:'<svg viewBox="0 0 24 24"><path d="M18 9a6 6 0 0 0-12 0c0 7-3 7-3 8h18c0-1-3-1-3-8"/><path d="M10 21h4"/></svg>',
 user:'<svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="4"/><path d="M4 21c.7-5 3.2-7.5 8-7.5s7.3 2.5 8 7.5"/></svg>',
 menu:'<svg viewBox="0 0 24 24"><path d="M4 7h16M4 12h16M4 17h16"/></svg>',
 x:'<svg viewBox="0 0 24 24"><path d="M6 6l12 12M18 6 6 18"/></svg>',
 chevron:'<svg viewBox="0 0 24 24"><path d="m9 6 6 6-6 6"/></svg>'
};
const modules={
 overview:{label:'Overview',landing:'admin-dashboard.html',product:null,pages:['admin-dashboard.html','admin-tasks.html'],groups:[['Company',[['admin-dashboard.html','Executive Overview'],['admin-tasks.html','Tasks & Follow-ups']]]]},
 testing:{label:'Testing',landing:'admin-orders.html',product:'screenings4u',pages:[],groups:[['Testing Operations',[['admin-orders.html','Testing Orders'],['admin-test-results.html','Test Results'],['admin-employers.html','Testing Customers'],['admin-scheduling.html','Scheduling'],['admin-documents.html','Documents']]],['Sales & Service',[['admin-quotes.html','Quotes'],['admin-proposals.html','Proposals'],['admin-forms.html','Forms']]]]},
 training:{label:'Training',landing:'admin-lms-dashboard.html',product:'training',pages:[],groups:[['Learning Center',[['admin-lms-dashboard.html','Training Overview'],['admin-lms-students.html','Students'],['admin-lms-courses.html','Courses'],['admin-lms-enrollments.html','Enrollments'],['admin-lms-certificates.html','Certificates']]],['Content',[['admin-lms-lessons.html','Lessons'],['admin-lms-assessments.html','Assessments'],['admin-lms-quizzes.html','Quizzes'],['admin-lms-media.html','Media']]]]},
 workforce:{label:'Workforce',landing:'admin-workforce.html',product:'workforce',pages:['admin-workforce.html'],groups:[['Workforce',[['admin-workforce.html','Workforce Operations'],['admin-customer-assignments.html','Customer Assignments']]]]},
 dot:{label:'DOT',landing:'admin-dot.html',product:'dot',pages:['admin-dot.html'],groups:[['DOT Compliance',[['admin-dot.html','DOT Operations'],['admin-customer-assignments.html','Customer Assignments']]]]},
 finance:{label:'Finance',landing:'admin-finance-ar.html',permission:c=>!c||c.super_admin||(c.permissions||[]).some(x=>String(x).startsWith('finance.')),pages:[],groups:[['Receivables',[['admin-finance-ar.html','Accounts Receivable'],['admin-invoices.html','Invoices'],['admin-invoice.html','Invoice Detail']]],['Payables',[['admin-finance-ap.html','Accounts Payable']]],['Commerce',[['admin-checkout.html','Checkout'],['admin-discounts.html','Discounts']]]]},
 customers:{label:'Customers',landing:'admin-customer-crm.html',pages:[],groups:[['Customer Operations',[['admin-customer-crm.html','Customer Accounts'],['admin-crm.html','CRM'],['admin-customer-chat.html','Customer Chat'],['admin-notifications.html','Notifications'],['admin-support-tickets.html','Support Queue']]]]},
 reports:{label:'Reports',landing:'admin-reports.html',pages:['admin-reports.html'],groups:[['Reporting',[['admin-reports.html','Executive Reports'],['admin-audit.html','Audit & Security']]]]} 
};
const explicit={
 'admin-dashboard.html':'overview','admin-tasks.html':'overview','admin-orders.html':'testing','admin-test-results.html':'testing','admin-employers.html':'testing','admin-employees.html':'testing','admin-employer-crm.html':'testing','admin-employer-users.html':'testing','admin-selection-employees.html':'testing','admin-search-submissions.html':'testing','admin-scheduling.html':'testing','admin-documents.html':'testing','admin-quotes.html':'testing','admin-quote.html':'testing','admin-proposals.html':'testing','admin-proposal.html':'testing','admin-forms.html':'testing','admin-blog.html':'testing','admin-seo.html':'testing','admin-url-redirects.html':'testing','admin-email-marketing.html':'testing',
 'admin-workforce.html':'workforce','admin-dot.html':'dot','admin-finance-ar.html':'finance','admin-finance-ap.html':'finance','admin-invoices.html':'finance','admin-invoice.html':'finance','admin-checkout.html':'finance','admin-discounts.html':'finance','admin-customer-crm.html':'customers','admin-crm.html':'customers','admin-customer-chat.html':'customers','admin-notifications.html':'customers','admin-support-tickets.html':'customers','admin-knowledge-base.html':'customers','admin-faqs.html':'customers','admin-reports.html':'reports'
};
function moduleForPage(){if(explicit[page])return explicit[page];if(page.startsWith('admin-lms-'))return'training';if(page.startsWith('admin-scheduling-'))return'testing';return'overview'}
function escapeHtml(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function initials(v='Administrator'){return String(v).split(/[\s._@-]+/).filter(Boolean).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()||'A'}
function visibleModules(){const c=state.ctx,prods=new Set((c?.product_access||[]).map(x=>x.product_code));return Object.entries(modules).filter(([_,m])=>{if(c?.super_admin)return true;if(m.product&&c&&prods.size&&!prods.has(m.product))return false;return !m.permission||m.permission(c)})}
const sidebarItems=[
 ['admin-dashboard.html','Home','home'],
 ['admin-orders.html','Testing Orders','testing'],
 ['admin-lms-dashboard.html','Training & Education','training'],
 ['admin-workforce.html','Workforce & Staff','workforce'],
 ['admin-dot.html','DOT Compliance','dot'],
 ['admin-customer-assignments.html','Customer Assignments','assignments'],
 ['admin-finance-ar.html','Finance','finance'],
 ['admin-customer-crm.html','CRM','crm'],
 ['admin-scheduling.html','Scheduling','schedule'],
 ['admin-documents.html','Documents','docs']
];
const adminItems=[
 ['admin-staff.html','Staff & Departments','staff'],
 ['admin-audit.html','Audit & Security','audit'],
 ['admin-global-settings.html','System Settings','settings'],
 ['admin-technology.html','Integrations','tech'],
 ['admin-support-tickets.html','Help & Support','help']
];
function navItem([href,label,icon]){const m=moduleForPage();let active=page===href;if(href==='admin-lms-dashboard.html'&&m==='training')active=true;if(href==='admin-workforce.html'&&m==='workforce')active=true;if(href==='admin-dot.html'&&m==='dot')active=true;if(href==='admin-finance-ar.html'&&m==='finance')active=true;if(href==='admin-customer-crm.html'&&m==='customers')active=true;if(href==='admin-orders.html'&&m==='testing'&&!page.startsWith('admin-scheduling'))active=true;if(href==='admin-scheduling.html'&&page.startsWith('admin-scheduling'))active=true;return `<a class="ep-side-link ${active?'active':''} ${href==='admin-dashboard.html'&&active?'home-active':''}" href="${href}"><span class="ep-side-icon">${ICONS[icon]}</span><span>${escapeHtml(label)}</span></a>`}
function sidebar(){return `<aside class="ep-sidebar"><div class="ep-brand"><a href="admin-dashboard.html"><img src="images/logo2.png" alt="screenings4u"><span>Workforce Compliance</span></a></div><nav class="ep-side-scroll" aria-label="Internal operations"><div class="ep-side-section">${navItem(sidebarItems[0])}</div><div class="ep-side-label">Operations</div><div class="ep-side-section">${sidebarItems.slice(1).map(navItem).join('')}</div><div class="ep-side-divider"></div><div class="ep-side-label">Administration</div><div class="ep-side-section">${adminItems.map(navItem).join('')}</div></nav><div class="ep-side-promo"><div class="ep-side-promo-image"></div><div class="ep-side-promo-copy"><strong>Safer People.<br>Stronger Workplaces</strong><span>Compliance today.<br>Opportunities tomorrow.</span><i></i></div></div></aside>`}
function tabDropdown(key,m){return `<div class="ep-biz-tab-wrap"><a class="ep-biz-tab ${moduleForPage()===key?'active':''}" href="${m.landing}">${escapeHtml(m.label)}</a><div class="ep-biz-dropdown">${m.groups.map(([title,links])=>`<section><span>${escapeHtml(title)}</span>${links.map(([href,label])=>`<a href="${href}">${escapeHtml(label)}</a>`).join('')}</section>`).join('')}</div></div>`}
function topbar(){const c=state.ctx,email=c?.user?.email||'Administrator',display=c?.profile?.display_name||c?.user?.user_metadata?.full_name||email.split('@')[0]||'Administrator',role=c?.roles?.[0]?.name||'Internal Staff';return `<div class="ep-top-brand"><button class="ep-mobile-menu" id="epMobileMenu" aria-label="Open navigation">${ICONS.menu}</button><div><strong>Workforce Compliance</strong><small>People Safe. Workplaces Stronger.</small></div></div><nav class="ep-business-tabs" aria-label="Business areas">${visibleModules().map(([k,m])=>tabDropdown(k,m)).join('')}</nav><div class="ep-top-actions"><button class="ep-top-icon" id="epSearchBtn" aria-label="Search" title="Search">${ICONS.search}</button><a class="ep-top-icon ep-notification-button" href="admin-notifications.html" aria-label="Notifications" title="Notifications">${ICONS.bell}<span class="ep-notify-dot" aria-hidden="true"></span></a><button class="ep-top-icon" id="epHelpBtn" aria-label="Help" title="Help">${ICONS.help}</button><div class="ep-user-menu"><button class="ep-user-toggle" id="epUserToggle"><span class="ep-avatar">${initials(display)}</span><span class="ep-user-copy"><strong>${escapeHtml(display)}</strong><small>${escapeHtml(role)}</small></span><span class="ep-user-caret">⌄</span></button><div class="ep-menu" id="epUserMenu"><div class="ep-menu-head"><div><strong>${escapeHtml(display)}</strong><small>${escapeHtml(email)}</small></div><button class="ep-menu-close" aria-label="Close">${ICONS.x}</button></div><a href="admin-accounts.html">Account & access</a><a href="admin-notifications.html">Notifications</a><a href="admin-support-tickets.html">Support center</a><button data-ep-logout>Sign out</button></div></div></div>`}
function searchIndex(){const x=[];for(const [k,m] of Object.entries(modules))for(const [group,links] of m.groups)for(const [href,label] of links)x.push({href,label,group,module:m.label});for(const [href,label] of [...sidebarItems,...adminItems])if(!x.some(i=>i.href===href))x.push({href,label,group:'Navigation',module:'Operations'});return x}
function overlays(){if(!$('.ep-overlay'))document.body.insertAdjacentHTML('beforeend','<div class="ep-overlay" id="epOverlay"></div>');if(!$('#epSearchModal'))document.body.insertAdjacentHTML('beforeend',`<div class="ep-search-modal" id="epSearchModal" aria-hidden="true"><div class="ep-search-dialog" role="dialog" aria-modal="true" aria-label="Search internal operations"><div class="ep-search-head"><span>${ICONS.search}</span><input id="epCommandSearch" type="search" placeholder="Search people, customers, invoices, or pages" autocomplete="off"><kbd>Ctrl K</kbd><button class="ep-search-close" aria-label="Close">${ICONS.x}</button></div><div class="ep-search-results" id="epCommandResults"><div class="ep-search-empty">Start typing to search the internal platform.</div></div></div></div>`);if(!$('#epHelpPanel'))document.body.insertAdjacentHTML('beforeend',`<div class="ep-help-panel" id="epHelpPanel"><div class="ep-help-head"><div><span>Support</span><strong>Need help?</strong></div><button class="ep-help-close" aria-label="Close">${ICONS.x}</button></div><p>Open the internal support queue, knowledge base, or audit trail without leaving your current business area.</p><a href="admin-support-tickets.html">Support queue</a><a href="admin-knowledge-base.html">Knowledge base</a><a href="admin-audit.html">Audit & security</a></div>`)}
function render(){document.body.classList.add('ep-enterprise-shell');const side=$('#admin-lms-sidebar-target');if(side)side.innerHTML=sidebar();let top=$('.admin-lms-topbar');if(!top){top=document.createElement('header');top.className='admin-lms-topbar';$('.admin-lms-main')?.prepend(top)}if(top)top.innerHTML=topbar();overlays();wire();}
function closeFloating(){$('#epUserMenu')?.classList.remove('open');$('#epHelpPanel')?.classList.remove('open');$('#epSearchModal')?.classList.remove('open');$('#epSearchModal')?.setAttribute('aria-hidden','true');document.body.classList.remove('ep-search-open');}
function openSearch(){const m=$('#epSearchModal');m?.classList.add('open');m?.setAttribute('aria-hidden','false');document.body.classList.add('ep-search-open');setTimeout(()=>$('#epCommandSearch')?.focus(),30)}
function wire(){const overlay=$('#epOverlay');$('#epMobileMenu')?.addEventListener('click',()=>document.body.classList.add('ep-mobile-open'));overlay?.addEventListener('click',()=>{document.body.classList.remove('ep-mobile-open');closeFloating()});$$('.ep-side-link').forEach(a=>a.addEventListener('click',()=>document.body.classList.remove('ep-mobile-open')));
 const menu=$('#epUserMenu');$('#epUserToggle')?.addEventListener('click',e=>{e.stopPropagation();$('#epHelpPanel')?.classList.remove('open');menu?.classList.toggle('open')});$('.ep-menu-close')?.addEventListener('click',()=>menu?.classList.remove('open'));document.addEventListener('click',e=>{if(!e.target.closest('.ep-user-menu'))menu?.classList.remove('open')});
 $('#epHelpBtn')?.addEventListener('click',e=>{e.stopPropagation();menu?.classList.remove('open');$('#epHelpPanel')?.classList.toggle('open')});$('.ep-help-close')?.addEventListener('click',()=>$('#epHelpPanel')?.classList.remove('open'));document.addEventListener('click',e=>{if(!e.target.closest('#epHelpPanel')&&!e.target.closest('#epHelpBtn'))$('#epHelpPanel')?.classList.remove('open')});
 $('#epSearchBtn')?.addEventListener('click',openSearch);$('.ep-search-close')?.addEventListener('click',closeFloating);$('#epSearchModal')?.addEventListener('click',e=>{if(e.target.id==='epSearchModal')closeFloating()});
 const input=$('#epCommandSearch'),results=$('#epCommandResults'),idx=searchIndex();if(input&&results){const run=()=>{const q=input.value.trim().toLowerCase();if(!q){results.innerHTML='<div class="ep-search-empty">Start typing to search the internal platform.</div>';return}const hits=idx.filter(x=>`${x.label} ${x.group} ${x.module} ${x.href}`.toLowerCase().includes(q)).slice(0,14);results.innerHTML=hits.map(x=>`<a href="${x.href}"><div><strong>${escapeHtml(x.label)}</strong><small>${escapeHtml(x.module)} · ${escapeHtml(x.group)}</small></div>${ICONS.chevron}</a>`).join('')||'<div class="ep-search-empty">No matching pages found.</div>'};input.addEventListener('input',run)}
 document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}if(e.key==='Escape'){document.body.classList.remove('ep-mobile-open');closeFloating()}});
 $('[data-ep-logout]')?.addEventListener('click',async()=>{try{await window.screenings4uSupabase?.auth?.signOut({scope:'local'})}finally{location.href='admin-login.html'}});
 // Add a visible close control to legacy floating surfaces without changing their business logic.
 $$('[role="dialog"],.modal,.dropdown-menu,.popover,.drawer').forEach(el=>{if(el.closest('#epSearchModal')||el.querySelector('[data-close],.modal-close,.ep-auto-close'))return;const b=document.createElement('button');b.type='button';b.className='ep-auto-close';b.innerHTML=ICONS.x;b.setAttribute('aria-label','Close');if(getComputedStyle(el).position==='static')el.style.position='relative';b.onclick=()=>{el.classList.remove('open','active','show');el.hidden=true};el.prepend(b)});
}
async function loadContext(){try{const sb=window.screenings4uSupabase;if(!sb?.functions)return;const {data,error}=await sb.functions.invoke('screenings4u-staff-context');if(!error&&data?.has_access)state.ctx=data}catch(e){console.warn('[Enterprise Shell] staff context unavailable',e)}}
async function init(){await loadContext();render();document.documentElement.classList.add('ep-ready')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,0));else setTimeout(init,0);
})();
